plugins {
    apply plugin: 'com.android.application'
apply plugin: 'org.jetbrains.kotlin.android' // Remove if pure Java
}

android {
    namespace 'com.jch.lposed'
    compileSdk 34

    defaultConfig {
        applicationId "com.jch.lposed"
        minSdk 27
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    compileOnly files('libs/api.aar')
    implementation files('libs/helper.aar')
}
